### ISSUE TITLE
Update docs to be better for new container users

### ISSUE THREAD

**Issue by AcerP-py** [olcf/velocity#11]

**Comment by ayarkhan** [comment]
https://github.com/olcf/velocity/blob/9d414879d8cd1f45256d0f05e3da8bb2080597cb/docs/source/starting/setup.rst?plain=1#L48
What version number should be used?
Suggest something in the comment.

----------
https://github.com/olcf/velocity/blob/9d414879d8cd1f45256d0f05e3da8bb2080597cb/docs/source/starting/setup.rst?plain=1#L55
Warning in output: ```2024-09-24 14:37:15.366 | WARNING  | velocity._config:get:55 - Could not find 'constraints' in config.```
Give a comment saying that is acceptable.

----------
https://github.com/olcf/velocity/blob/9d414879d8cd1f45256d0f05e3da8bb2080597cb/docs/source/starting/tutorial.rst?plain=1#L61
Warning in output: ```2024-09-24 14:47:36.057 | WARNING  | velocity._config:get:55 - Could not find 'constraints' in config.```

----------
https://github.com/olcf/velocity/blob/9d414879d8cd1f45256d0f05e3da8bb2080597cb/docs/source/starting/tutorial.rst?plain=1#L69

Error while building.
```
frontier:login12:/tmp/velocity$ velocity build fedora
2024-09-24 14:49:28.824 | WARNING  | velocity._config:get:55 - Could not find 'constraints' in config.
==> Build Order:
    fedora@38-e50b95e

==> e50b95e: BUILD fedora@38 ...
==> e50b95e: GENERATING SCRIPT ...
==> e50b95e: BUILDING ...
    INFO:    User not listed in /etc/subuid, trying root-mapped namespace
    INFO:    The %post section will be run under fakeroot
    INFO:    Starting build...
    Copying blob sha256:633a2a041c85d22a814d80c8fd43a885066522afeea82db646cff81983f3dbaf
    Copying config sha256:15e89348c0c8ee6a8ba51a734ab807d6c780cf23212ff5d632b96d4bbaff5193
    Writing manifest to image destination
    2024/09/24 14:49:33  info unpack layer: sha256:633a2a041c85d22a814d80c8fd43a885066522afeea82db646cff81983f3dbaf
    2024/09/24 14:49:35  warn xattr{var/spool/mail} ignoring ENOTSUP on setxattr "user.rootlesscontainers"
    2024/09/24 14:49:35  warn xattr{/tmp/build-temp-1377047072/rootfs/var/spool/mail} destination filesystem does not support xattrs, further warnings will be suppressed
    INFO:    Running post scriptlet
    /.singularity.d/libs/fakeroot: line 46: getopt: command not found
    /.singularity.d/libs/fakeroot: line 50: getopt: command not found
    fakeroot, create a fake root environment.
       usage: fakeroot [-l|--lib fakerootlib] [-f|--faked fakedbin]
                       [-i file] [-s file] [-u|--unknown-is-real]
                   [-b|--fd-base fd] [-h|--help] [-v|--version]
                       [--] [command]
    FATAL:   While performing build: while running engine: exit status 1
frontier:login12:/tmp/velocity$
```

----------
https://github.com/olcf/velocity/blob/9d414879d8cd1f45256d0f05e3da8bb2080597cb/docs/source/starting/tutorial.rst?plain=1#L80
The actual verbose output is probably not needed.

----------

**Comment by AcerP-py** [comment]
@ayarkhan regarding the build error see https://github.com/apptainer/apptainer/issues/1863. I think the easiest solution is to switch to another distro for the example.

**Comment by ayarkhan** [comment]
https://github.com/olcf/velocity/blob/ca622acc1d33c5fdd9c72039c70036e6d5159c5d/docs/source/starting/tutorial.rst?plain=1#L197

My image had a different name "x86_64" instead of "frontier"
==> BUILT: /tmp/velocity/hello-world-1.0_opensuse-15.6__x86_64-opensuse.sif

So the "apptainer run" had to be changed.
Would  "apptainer run hello-world-*-opensuse.sif" be reasonable?

**Comment by ayarkhan** [comment]
https://github.com/olcf/velocity/blob/ca622acc1d33c5fdd9c72039c70036e6d5159c5d/docs/source/starting/tutorial.rst?plain=1#L577-L584

I don't have podman in my install, so not tested.

**Comment by ayarkhan** [comment]
https://github.com/olcf/velocity/blob/ca622acc1d33c5fdd9c72039c70036e6d5159c5d/docs/source/starting/tutorial.rst?plain=1#L615

I don't think the list of hello-world directories is needed.

**Comment by ayarkhan** [comment]
https://github.com/olcf/velocity/blob/ca622acc1d33c5fdd9c72039c70036e6d5159c5d/docs/source/starting/usage.rst?plain=1#L57

Perhaps use opensuse rather than ubuntu.
Ubuntu fails for me.

**Comment by ayarkhan** [comment]
https://github.com/olcf/velocity/blob/ca622acc1d33c5fdd9c72039c70036e6d5159c5d/docs/source/starting/usage.rst?plain=1#L73

Maybe use opensuse
```
velocity build opensuse mpich
2024-09-25 17:10:49.888 | WARNING  | velocity._config:get:55 - Could not find 'constraints' in config.
==> Build Order:
    opensuse@15.6-5d9dbfe
    mpich@3.4.3-cabd296

==> 5d9dbfe: BUILD opensuse@15.6 ...
==> 5d9dbfe: GENERATING SCRIPT ...
==> 5d9dbfe: BUILDING ...
==> 5d9dbfe: IMAGE /tmp/velocity/build/opensuse-15.6-5d9dbfe/5d9dbfe.sif (opensuse@15.6) BUILT [0:00:00]

==> cabd296: BUILD mpich@3.4.3 ...
==> cabd296: GENERATING SCRIPT ...
==> cabd296: BUILDING ...
==> cabd296: IMAGE /tmp/velocity/build/mpich-3.4.3-cabd296/cabd296.sif (mpich@3.4.3) BUILT [0:04:09]

==> BUILT: /tmp/velocity/mpich-3.4.3_opensuse-15.6__x86_64-opensuse.sif
```

**Comment by ayarkhan** [comment]
Just general comment, the following warning remains.
```
2024-09-25 17:10:49.888 | WARNING  | velocity._config:get:55 - Could not find 'constraints' in config.
```

**Comment by ayarkhan** [comment]
https://github.com/olcf/velocity/blob/ca622acc1d33c5fdd9c72039c70036e6d5159c5d/docs/source/starting/setup.rst?plain=1#L40

Alternatively, you can clone

**Comment by ayarkhan** [comment]
https://github.com/olcf/velocity/blob/ca622acc1d33c5fdd9c72039c70036e6d5159c5d/docs/source/starting/tutorial.rst?plain=1#L39

opensuse/specs.yaml

**Comment by ayarkhan** [comment]
https://github.com/olcf/velocity/blob/ca622acc1d33c5fdd9c72039c70036e6d5159c5d/docs/source/starting/tutorial.rst?plain=1#L48

opensuse/templates/default.vtmp

**Comment by ayarkhan** [comment]
https://github.com/olcf/velocity/blob/ca622acc1d33c5fdd9c72039c70036e6d5159c5d/docs/source/starting/tutorial.rst?plain=1#L109

opensuse@15.6`\

**Comment by ayarkhan** [comment]
https://github.com/olcf/velocity/blob/ca622acc1d33c5fdd9c72039c70036e6d5159c5d/docs/source/starting/tutorial.rst?plain=1#L134

hello-world/files/hello_world.py

**Comment by ayarkhan** [comment]
https://github.com/olcf/velocity/blob/ca622acc1d33c5fdd9c72039c70036e6d5159c5d/docs/source/starting/tutorial.rst?plain=1#L141

hello-world/specs.yaml

**Comment by ayarkhan** [comment]
https://github.com/olcf/velocity/blob/ca622acc1d33c5fdd9c72039c70036e6d5159c5d/docs/source/starting/tutorial.rst?plain=1#L153

hello-world/templates/default.vtmp

**Comment by ayarkhan** [comment]
https://github.com/olcf/velocity/blob/ca622acc1d33c5fdd9c72039c70036e6d5159c5d/docs/source/starting/tutorial.rst?plain=1#L346

hello-world/specs.yaml
